/* Uma exceção é um problema que ocorre durante a execução de um programa que pode interromper o seu funcionamento ou
não executá-lo da forma esperada. Todas as exceções são herdadas, direta ou indiretamente, da classe "Exception", que herda da
classe "Throwable". 
Existem as exceções verificadas, que herdam da classe "Exception" e as não-verificadas, que herdam da classe "RunTimeException".
As exceções que herdam de "RunTimeException" irão terminar a execução do programa ou este terminará com dados inesperados.
As exceções verificadas pode sem tratadas utilizando "try-catch". O "try" contém o bloco de código que poderá lançar a exceção
e o "catch" contém o bloco de código que irá tratar a exceção caso esta seja lançada.

*/